Added env variable that enables/disables progress bar
mozilla/sign-addon pull request #775
Opened 2021-05-12 15:49 UTC by manthony9

Running node run-sign-addon.js n would disable the progress bar. Running it without any arguments would run the file with the progress bar. Added setProOptions function in PseudoProgress.js that assigns environment variable to local variable. A validation is performed in the show bucket function and executes the required action.

2021-05-13 10:23 UTC, Rob--W commented
It looks like you're testing the functionality against a live demo server.
A unit test should ideally be self-contained and be independent of external dependencies.

Could you add a unit test? See https://github.com/mozilla/sign-addon/tree/master/tests for existing examples.

2021-05-13 14:12 UTC, manthony9 commented
@Rob--W Working on it. Will share an update as soon as I'm done.

2021-05-14 17:14 UTC, manthony9 commented
Hi @Rob--W, I tried making a small test in PseduoProgress.spec.ts not sure if it's the right approach, any feedback to improve would help. PseduoProgress.spec.js passes in general but import.spec.js fails. I haven't made any changes to import.spec . Snapshots below for your reference.

Failed Test
![image](https://user-images.githubusercontent.com/13238071/118305427-f22c4580-b4b5-11eb-9cf1-4bc1b5f19b92.png)
Passed Test
![image](https://user-images.githubusercontent.com/13238071/118305462-007a6180-b4b6-11eb-9be6-face466961ca.png)
My addition to PseudoProgress.spec.ts
![image](https://user-images.githubusercontent.com/13238071/118305506-112ad780-b4b6-11eb-91cb-3771ded49941.png)

2021-05-31 10:06 UTC, willdurand requested changes
That's a good start but we should take a slightly different direction.

2021-05-31 10:06 UTC, willdurand commented on run-sign-addon.js
> +var { signAddon } = require('./dist/sign-addon.js');
You should remove this file as well as the following ones:

- manifest.json
- cobster_loraboon_giraccork-1.0-an+fx.xpi
- cobster-loraboon-giraccork.zip

2021-05-31 10:06 UTC, willdurand commented on src/PseudoProgress.js
> +    this.proOptions = process.argv[2];
I think we want to pass this setting from the `signAddon` function. It could be a new parameter in the constructor.

2021-08-09 13:10 UTC, willdurand commented
The issue has been closed by another patch.

2021-08-09 13:10 UTC, closed without merging